### ISSUE TITLE
Uncaught Exception: Expected 48 got 47

### ISSUE THREAD

**Issue by Pr0x1m4** [zeit/hyperterm#3]
Exception occurs after trying to run `npm run launch` and produces this error.

```javascript
> hyperterm@0.1.0 launch /home/proxima/Desktop/hyperterm-0.1.0
> electron index

App threw an error during load
Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/proxima/Desktop/hyperterm-0.1.0/node_modules/child_pty/lib/child_pty.js:1:90)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/proxima/Desktop/hyperterm-0.1.0/node_modules/child_pty/lib/child_pty.js:1:90)

```
Node & npm versions
node -v5.1.0
npm -v3.8.1

OS
Arch Linux 4.6.2

**Comment by rauchg** [comment]
@Pr0x1m4 I'll add instructions for development. It has to do with installing the native modules with the appropriate flags for electron.

**Comment by rauchg** [comment]
@Pr0x1m4 done! Let me know if those instructions work for you. If so, feel free to close the issue.

**Comment by Pr0x1m4** [comment]
Works fine now
![2016-07-02-163941_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4820517/16542587/8b58c104-4074-11e6-85dc-83c4731734f4.png)
