### ISSUE TITLE
Uncaught Exception: Error: watch

### ISSUE THREAD

**Issue by MrRio** [zeit/hyperterm#564]
**A JavaScript error occurred in the main process**

```
Uncaught Exception:
Error: watch /Users/jameshall/latest ENOENT
    at exports._errnoException (util.js:1008:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at Gaze._watchDir (/Users/jameshall/Code/hyperterm/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Users/jameshall/Code/hyperterm/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Users/jameshall/Code/hyperterm/app/node_modules/gaze/lib/helper.js:69:5)
    at /Users/jameshall/Code/hyperterm/app/node_modules/gaze/lib/helper.js:78:11
    at /Users/jameshall/Code/hyperterm/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Users/jameshall/Code/hyperterm/app/node_modules/gaze/lib/helper.js:69:5)
    at Object.forEachSeries (/Users/jameshall/Code/hyperterm/app/node_modules/gaze/lib/helper.js:83:3)\
```
<img width="532" alt="screen shot 2016-08-04 at 23 17 44" src="https://cloud.githubusercontent.com/assets/47539/17420261/ac98c438-5a99-11e6-8bc3-77d8aa2cdeee.png">

This is the latest build after being packaged for release.

**Comment by MrRio** [comment]
Apologies, this is a dupe of https://github.com/zeit/hyperterm/issues/542
