### ISSUE TITLE
Cannot find module 'file-uri-to-path'

### ISSUE THREAD

**Issue by jpka** [zeit/hyperterm#566]
On linux, Ubuntu 16.04 latest master, also persists if I install file-uri-to-path manually and then build

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'file-uri-to-path'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/home/jpka/bin/hyperterm/dist/linux/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jpka/bin/hyperterm/dist/linux/resources/app/index.js:7:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by MrRio** [comment]
CC @lordgiotto

**Comment by MrRio** [comment]
This works alright from me when running 'npm start' on OSX.

**Comment by jpka** [comment]
@MrRio This is when building with 'npm run pack'

**Comment by MrRio** [comment]
Fixed in referenced PR. :)

**Comment by MrRio** [comment]
@jpka thanks for submitting

**Comment by jpka** [comment]
Np, thanks for fixing
