### ISSUE TITLE
JavaScript error on quit when web view is/was showing

### ISSUE THREAD

**Issue by booc0mtaco** [zeit/hyperterm#631]
Steps to reproduce (on latest release):

1. Open new hyperterm instance
2. Type in a URL (e.g., <http://www.google.com/>)
3. Once loaded, quit the app ( + q **or** "Quit Hyperterm")

Instead of quitting normally, it generates the following error:

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at sendWrapper (/Applications/HyperTerm.app/Contents/Resources/electron.asar/browser/api/web-contents.js:107:24)
    at EventEmitter.<anonymous> (/Applications/HyperTerm.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:136:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
```

This happens even when you close the window that had the view, and open another window, then quit.

**version**: `Version 0.7.1 (0.7.1.36)`

**Comment by MrRio** [comment]
Can you try on latest master? I think this may have been fixed.

**Comment by ppot** [comment]
Just tested this issue. There is no exception on `cmd+q` , but there is one on Quit Hyperterm.

**Comment by ryangun** [comment]
+1
If I have opened a web page on a tab, w
![qq20160825-0 2x](https://cloud.githubusercontent.com/assets/3684807/17958160/126984d8-6aca-11e6-8f1d-039ca54a0439.png)
hen I quit the hyperterm (command+q), the error occurs.

**Comment by obrassard** [comment]
+1 
>**A JavaScript error occurred in the main proccess**
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at WebContents.send (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:93:15)
    at sendToEmbedder (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:121:16)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:128:7)
    at emitOne (events.js:101:20)
    at WebContents.emit (events.js:188:7)

**Comment by amonks** [comment]
I consistently see this error on quit _if and only if_ I open a new tab while a web view is open.

Additionally, whenever I open a web view (any website) I get this in the console:

```
bundle.js:18446 Uncaught RangeError: Maximum call stack size exceeded.__WEBPACK_IMPORTED_MODULE_0_hterm_umdjs__.hterm.Terminal.focusHyperCaret @ bundle.js:18446handleFocus @ bundle.js:17349invokeGuardedCallback @ bundle.js:6815executeDispatch @ bundle.js:5913executeDispatchesInOrder @ bundle.js:5936executeDispatchesAndRelease @ bundle.js:2994forEachAccumulated @ bundle.js:13804processEventQueue @ bundle.js:3181runEventQueueInBatch @ bundle.js:47094handleTopLevel @ bundle.js:47105handleTopLevelImpl @ bundle.js:47188perform @ bundle.js:3607batchedUpdates @ bundle.js:46975batchedUpdates @ bundle.js:1617dispatchEvent @ bundle.js:47265webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102webviewNode.addEventListener @ web-view.js:102
```

video demonstration: https://vimeo.com/195741316

**Comment by RobinMalfait** [comment]
I also still have this bug 

![](http://d.rbn.nu/OuT0l+)

It happens for me when:

1. Open Hyper
2. CMD+D to split into panes
3. type https://google.com
4. press enter to load google
5. cmd+q

**Comment by ppot** [comment]
Already know. Yes

**Comment by ErEllison** [comment]
same here 
![Uploading Sketch.png…]()

**Comment by thmsbfft** [comment]
👋

I don't know how relevant that might still be but I use a similar `rpc.js` as Hyper and ran into the same issue. Passing the server's `id` to `this.wc.removeAllListeners()` when destroying the instance fixed it for me. You can see the commit [here](https://github.com/thmsbfft/oryoki/commit/9533615c5145134ad3733c27e0bd8b142f913295#diff-a59638ed544fe3c9e8f6b2ddd93a7343R48). I'd do a PR but I'm not that familiar with the whole process. Hope this can help!

**Comment by Sriram-Sridhar** [comment]
- Same happened for me

> Uncaught Exception:
> Error: Object has been destroyed
>     at notify (/Applications/Hyper.app/Contents/Resources/app.asar/notify.js:36:8)
>     at FSWatcher.onChange (/Applications/Hyper.app/Contents/Resources/app.asar/config.js:19:5)
>     at emitTwo (events.js:106:13)
>     at FSWatcher.emit (events.js:194:7)
>     at FSEvent.FSWatcher._handle.onchange (fs.js:1392:12)

**Comment by micsel** [comment]
For me, changing "closed" to "close" worked!
win.on('close', () => { win = null }

**Comment by Stanzilla** [comment]
@chabou ^
