### ISSUE TITLE
Uncaught exceptions when doing "vagrant up".

### ISSUE THREAD

**Issue by pauldotknopf** [zeit/hyperterm#680]
Title says it all. I think the stdout from ```vagrant up``` is doing some weird things.

```
Uncaught Exception:
Error: watch /Users/pknopf/.vagrant.d/tmp/vagrant-box-add-temp-20160831-45752-rzesh ENOENT
    at exports._errnoException (util.js:949:11)
    at FSWatcher.start (fs.js:1433:19)
    at Object.fs.watch (fs.js:1460:11)
    at Gaze._watchDir (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
```

**Comment by matheuss** [comment]
Closing in favor of #225
