### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by deeperx** [zeit/hyperterm#706]
While the app is in background and I wasn't doing anything with it for a few hours; A popup error message appeared.

```javascript
Uncaught Exception:
Error: watch /Users/inanc/.hyperterm_plugins/node_modules/.staging ENOENT
    at exports._errnoException (util.js:949:11)
    at FSWatcher.start (fs.js:1433:19)
    at Object.fs.watch (fs.js:1460:11)
    at Gaze._watchDir (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
```

<img width="532" alt="screen shot 2016-09-11 at 23 05 52" src="https://cloud.githubusercontent.com/assets/621232/18420156/7ac87ee6-7874-11e6-82c7-e3a8e34dbf62.png">

**Comment by c0b41** [comment]
dups #225

**Comment by deeperx** [comment]
@c0b41 Are you sure it is dup? See the error message. It's different.
