### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 47

### ISSUE THREAD

**Issue by afshinm** [zeit/hyperterm#72]
Hey guys,

Just tried to run the app but I'm getting this error:
```

➜  hyperterm-master npm start

> hyperterm@0.3.1 start /Users/afshin/Downloads/hyperterm-master
> electron index

App threw an error during load
Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/afshin/Downloads/hyperterm-master/node_modules/child_pty/lib/child_pty.js:1:90)

```

Is this related to Electron?

**Comment by rauchg** [comment]
You have to install with `./install.sh` instead of `npm install`.

**Comment by rauchg** [comment]
I welcome a PR that adds a `try/catch` around that module and warns that most likely you didn't install correctly.

**Comment by afshinm** [comment]
cheers @rauchg. Will send a PR tonight.
