### ISSUE TITLE
An error occured in redux-logger

### ISSUE THREAD

**Issue by outsideris** [zeit/hyperterm#746]
<img width="690" alt="2016-09-25 20 26 00" src="https://cloud.githubusercontent.com/assets/390146/18815009/776d6dd4-835e-11e6-82e3-b7efc619af3e.png">

When I run `npm start`, there is an error in [redux-logger](https://github.com/evgenyrodionov/redux-logger/blob/master/src/core.js#L31), because `actions` from `logEntry` is `undefined`.

```
Error: Actions must be plain objects. Use custom middleware for async actions.
    at Object.performAction (<anonymous>:1:17701)
    at dispatch (<anonymous>:1:15619)
    at eval (eval at <anonymous> (file:///Users/outsider/hyperterm/app/dist/bundle.js:1984:1), <anonymous>:208:29)
    at action (eval at <anonymous> (file:///Users/outsider/hyperterm/app/dist/bundle.js:624:1), <anonymous>:9:15)
    at action (eval at <anonymous> (file:///Users/outsider/hyperterm/app/dist/bundle.js:121:1), <anonymous>:382:30)
    at EventEmitter.__WEBPACK_IMPORTED_MODULE_5__rpc__.a.on (eval at <anonymous> (file:///Users/outsider/hyperterm/app/dist/bundle.js:2051:1), <anonymous>:57:10)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.Client.ipc.on (eval at <anonymous> (file:///Users/outsider/hyperterm/app/dist/bundle.js:1126:1), <anonymous>:23:22)
    at emitTwo (events.js:106:13)
```

Am I missed something?

**Comment by outsideris** [comment]
My environments are:

* OS X
* Node.js 6.6.0

**Comment by outsideris** [comment]
I guess this error occurred from [here](https://github.com/zeit/hyperterm/blob/master/lib/index.js#L37). `init()` is async operations. Following snippets look to fix the error, but I'm not sure about it.

```diff
--- a/lib/actions/index.js
+++ b/lib/actions/index.js
@@ -1,5 +1,7 @@
 import rpc from '../rpc';

 export function init() {
-  rpc.emit('init');
+  return dispatch => {
+    rpc.emit('init');
+  };
 }
```

**Comment by ppot** [comment]
[#675]

**Comment by outsideris** [comment]
@ppot Thanks, I missed it.
